name: Publishes a new version of the templates
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Release maven packages
        uses: qcastel/github-actions-maven-release@v1.12.41
        env:
          JAVA_HOME: /usr/lib/jvm/java-21-openjdk/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@sheldan.dev"
          release-branch-name: master
          maven-args: "-Dmaven.javadoc.skip=true -s settings.xml -DskipTests"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          author_email: "release-bot@sheldan.dev"